#Eureka server服务端⼝
server:
  port: 8762
spring:
  aplication:
    name: lagou-cloud-eureka-server    #应用名称，应用名称会在Eureka中作为服务名称


    #Eureka客户端配置（和Server交互），Eureka Server其实也是一个Client
eureka:
  instance:
    hostname: LagouCloudEurekaServerB  #当前Eureka实例的主机名
    prefer-ip-address: true   #服务器实例中显示IP
    instance-id: ${spring.cloud.client.ip-address}:${spring.aplication.name}:${server.port}:@project.version@
  client:
    service-url:   #配置客户端所交互的Eureka Server地址
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka/
    register-with-eureka: true   #当前自己就是Server，不需要注册自己
    fetch-registry: true   #查询获取注册中心的服务信息，自己就是server，不需要从Eureka Server获取服务信息，默认为true

